title: Hello! I'm Prasanta Halder
description: > # this means to ignore newlines until "baseurl:"
  This is Prasanta Halder's Website. 
  This mainly deal with my project details and timepass posts.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Prasanta Halder # add your name
author-img: prasanta-halder.jpg # add your photo
about-author: I am a FPGA developer focusing on VHDL/Verilog. Always hungry to keep learning. # add description
social-twitter: prasa # add your Twitter handle
social-facebook: prasanta.halder50# add your Facebook handle
social-github: prasa # add your Github handle
social-linkedin: prasantahalder# add your Linkedin handle
social-email: prasanta.etc@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
