title: Hello! I'm Prasanta
description: > # this means to ignore newlines until "baseurl:"
  This is Prasanta Halder's Blog. 
  This mainly deal with my project details and blog posts.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prashal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Prasanta Halder # add your name
author-img: prasanta-halder.jpg # add your photo
about-author: Embedded hardware designer by profession and software enthusiast by choice. A keen learner and voracious programmer. # add description
social-twitter: prasa # add your Twitter handle
social-facebook: prasanta.halder50 # add your Facebook handle
social-github: prashal # add your Github handle
social-linkedin: prashal # add your Linkedin handle
social-email: prasanta.etc@live.com # add your Email address

# Disqus
discus-identifier: prashal-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Syntax Highlighter
highlighter: rouge

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/blog/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
